# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02053afe0bf171e2c7480d274dab5e83f9647ad8c8487f581050a735b92feaebe7aa94c8059d6bce5e011ef21315a0286c45b3009b4ae187e052e9d716619306

test:
  secret_key_base: 1b3e8adbc8b26e1a92f0558c55d9af911a4d5f87a8ab3b315f5e3c29fcb104eb0225b81ee18c197ddb4c9cdd71fa7ef748d6cbe51423d1cd0e32b77f000d7e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
